/*
    Warning - this file was autogenerated by genparse
    DO NOT EDIT - any changes will be lost
*/

#include "aghfp_parse.h"

#include <ctype.h>
#include <panic.h>
#include <stdlib.h>
#include <stdio.h>
#include <string.h>
#include <util.h> /* hash and compare */

#if (defined TEST_HARNESS || defined DISPLAY_AT_CMDS)
#include <stdio.h>
#endif

#if defined(__KALIMBA__) && !defined(__GNUC__)
/* suppress warning caused for 'res' as compiler does not track into calls */
#pragma unitsuppress PossiblyUninitialized
#endif

typedef const uint8 *ptr;

static __inline__ char my_toupper(char c)
{ return (char)('a' <= c && c <= 'z' ? c +'A'-'a' : c); }

static ptr skip1(ptr s, ptr e)
{
  if(s)
    while(s != e && (*s == ' ' || *s == '\t'))
      ++s;
  return s;
}

#ifdef TEST_HARNESS
static void printString(const char *name, const struct sequence *s)
{
  uint16 i;
  printf(" %s='", name);
  for(i = 0; i < s->length; ++i) putchar(s->data[i]);
  printf("'");
}
#endif

static __inline__ ptr skipQuote(ptr p, ptr e)
{ return p && p != e && *p == '"' ? p+1 : p; }

static const int isStringTable[] =
{
    0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
    0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
    1,0,0,1,0,1,0,1,1,1,1,1,0,1,0,1,
    1,1,1,1,1,1,1,1,1,1,0,0,0,0,0,0,
    0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,
    1,1,1,1,1,1,1,1,1,1,1,0,1,0,1,1,
    0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,
    1,1,1,1,1,1,1,1,1,1,1,0,0,0,0,0
};

static __inline__ int isString(char c)
{
    return (c & ~0x7F) == 0 && isStringTable[(int)c];
}

static ptr getString(ptr p, ptr e, struct sequence *res)
{
  p = skipQuote(p, e);
  if(p)
  {
    ptr s = p;
    while(p != e && isString(*p)) ++p;
    if(p != s)
    {
        res->data = s;
        res->length = (uint16)(p - s);
        return skipQuote(p, e);
    }
    else
    {
        p = skipQuote(p, e);
        if (*p==',' || *p == '\r')
        {
            res->data = 0;
            res->length = 0;
            return p;
        }
    }
  }
  res->data = 0;
  res->length = 0;
  return 0;
}

static ptr skipOnce1(ptr s, ptr e)
{
  if(s)
  {
    if(s != e && (*s == ',' || *s == ';'))
      ++s;
  }
  return s;
}

static ptr match1(ptr s, ptr e)
{ return s && s != e && (*s == '\r' || *s == '\n') ? s+1 : 0; }

static ptr matchChar(ptr s, ptr e, uint8 c)
{ return s && s != e && my_toupper((char) *s) == (char) c ? s+1 : 0; }

struct value_aghfpHandleAvailableCodecs_codecs get_aghfpHandleAvailableCodecs_codecs(const struct region_aghfpHandleAvailableCodecs_codecs *r0, uint16 i)
{
  union {
    const struct region_aghfpHandleAvailableCodecs_codecs * c;
    struct region_aghfpHandleAvailableCodecs_codecs * nc;
  } const_workaround;
  struct region_aghfpHandleAvailableCodecs_codecs * r;
  const_workaround.c = r0;
  r = const_workaround.nc;
  if(i < r->next)
  {
    r->next   = 0;
    r->next_s = r->s;
  }
  {
    uint16 n = r->next;
    ptr p = r->next_s;
    ptr e = r->e;
    struct value_aghfpHandleAvailableCodecs_codecs res;
    while(p && p != e && n <= i)
    {
      ++n;
      p = skip1(skipOnce1(skip1(UtilGetNumber(p, e, &res.codec), e), e), e);
    }
    r->next   = n;
    r->next_s = p;
    return res;
  }
}

static ptr loop1(ptr p, ptr e, struct region_aghfpHandleAvailableCodecs_codecs *res)
{
  int n = 0;
  struct value_aghfpHandleAvailableCodecs_codecs dummy;
  res->s = p;
  while(p && p != e && n < 10)
  {
    ptr pp = UtilGetNumber(p, e, &dummy.codec);
    if(!pp) break; else p = pp;
    if(++n < 10)
      p = skip1(skipOnce1(skip1(p, e), e), e);
  }
  res->e      = p;
  res->count  = (uint16)n;
  res->next   = 0;
  res->next_s = res->s;
  return 1 <= n ? p : 0;
}

static ptr getWildString(ptr p, ptr e, struct sequence *res)
{
  if(p)
  {
    ptr s = p;
    p = (uint8*)UtilFind(0xFFFF, '\r', (const uint16*)p, 0, 1, (uint16) (e - p));
    if (!p) p = (uint8*)UtilFind(0xFFFF, '\n', (const uint16*)p, 0, 1, (uint16) (e - p));
    if (!p) p = e;
    res->data = s;
    res->length = (uint16)(p - s);
    return p;
  }
  res->data = 0;
  res->length = 0;
  return 0;
}

struct value_aghfpHandleBindParse_indicators get_aghfpHandleBindParse_indicators(const struct region_aghfpHandleBindParse_indicators *r0, uint16 i)
{
  union {
    const struct region_aghfpHandleBindParse_indicators * c;
    struct region_aghfpHandleBindParse_indicators * nc;
  } const_workaround;
  struct region_aghfpHandleBindParse_indicators * r;
  const_workaround.c = r0;
  r = const_workaround.nc;
  if(i < r->next)
  {
    r->next   = 0;
    r->next_s = r->s;
  }
  {
    uint16 n = r->next;
    ptr p = r->next_s;
    ptr e = r->e;
    struct value_aghfpHandleBindParse_indicators res;
    while(p && p != e && n <= i)
    {
      ++n;
      p = skip1(skipOnce1(skip1(UtilGetNumber(p, e, &res.indicator), e), e), e);
    }
    r->next   = n;
    r->next_s = p;
    return res;
  }
}

static ptr loop2(ptr p, ptr e, struct region_aghfpHandleBindParse_indicators *res)
{
  int n = 0;
  struct value_aghfpHandleBindParse_indicators dummy;
  res->s = p;
  while(p && p != e && n < 10)
  {
    ptr pp = UtilGetNumber(p, e, &dummy.indicator);
    if(!pp) break; else p = pp;
    if(++n < 10)
      p = skip1(skipOnce1(skip1(p, e), e), e);
  }
  res->e      = p;
  res->count  = (uint16)n;
  res->next   = 0;
  res->next_s = res->s;
  return 1 <= n ? p : 0;
}

static ptr skip2(ptr s, ptr e)
{
  if(s)
    while(s != e && (*s == '?'))
      ++s;
  return s;
}

static ptr skip3(ptr s, ptr e)
{
  if(s)
    while(s != e && (*s == '(' || *s == ')'))
      ++s;
  return s;
}

static ptr findEndOfPacket(ptr s, ptr e)
{
  /*
     Returns
     0   if the buffer holds an incomplete packet
     s+1 if the buffer holds an invalid packet
     end of the first packet otherwise
  */
  if(s == e) return 0;

  if(*s == '\r')
  {
    /* expecting <cr> <lf> ... <cr> <lf> */
    if(e-s >= 4)
    {
      if(s[1] == '\n' && s[2] != '\r')
      {
        ptr p = s+2;
        if(*p != '\r')
        {
#ifndef TEST_HARNESS
        p = (const uint8*)UtilFind(0xFFFF, '\r', (const uint16*)p, 0, 1, (uint16)(e-p));
#endif
#ifdef TEST_HARNESS
		   while(p != e && *p != '\r') p++;
#endif
        return p == 0 || p + 1 == e ? 0 /* no terminator yet */
             : p[1] == '\n' ? p+2 /* valid */
             : s+1 ; /* invalid terminator */
         }
         else
             return s+1;
      }
      else
      {
        return s+1;
      }
    }
    else
    {
      /* Can't tell yet */
      return 0;
    }
  }
  else
  {
    /* expecting ... <cr> */
    ptr p = s;
    while(p != e && (*p == ' ' || *p == '\0' || *p == '\t')) ++p;
    if(p != e && (*p == '\r' || *p == '\n' )) return s+1;
    while(p != e && *p != '\r') ++p;
    return p == e ? 0 : p+1;
  }
}

#ifndef TEST_HARNESS
#ifdef __XAP__
uint16 parseSource(Source rfcDataIn, Task task)
{
  ptr s = SourceMap(rfcDataIn);
  ptr e = s + SourceSize(rfcDataIn);
  ptr p = parseData(s, e, task);
  if(p != s)
  {
    SourceDrop(rfcDataIn, (uint16) (p - s));
    return 1;
  }
  else
  {
    return 0;
  }
}
#endif
#endif

typedef struct {
  char c;
  int to;
} Arc;

static const Arc arcs[] = {
  { '\t', 0 },
  { ' ', 0 },
  { 'A', 1 },
  { 'T', 2 },
  { '\t', 3 },
  { ' ', 3 },
  { '+', 4 },
  { 'A', 5 },
  { 'D', -1 },
  { '\t', 3 },
  { ' ', 3 },
  { '+', 4 },
  { '\t', 4 },
  { ' ', 4 },
  { 'B', 6 },
  { 'C', 7 },
  { 'N', 8 },
  { 'V', 9 },
  { '\t', 5 },
  { '\n', -2 },
  { '\r', -2 },
  { ' ', 5 },
  { 'A', 10 },
  { 'C', 11 },
  { 'I', 12 },
  { 'L', 13 },
  { 'R', 14 },
  { 'T', 15 },
  { 'V', 16 },
  { 'C', 17 },
  { 'H', 18 },
  { 'I', 19 },
  { 'K', 20 },
  { 'L', 21 },
  { 'M', 22 },
  { 'N', 23 },
  { 'O', 24 },
  { 'S', 25 },
  { 'R', 26 },
  { 'G', 27 },
  { 'T', 28 },
  { 'C', 29 },
  { 'C', 30 },
  { 'S', 31 },
  { 'A', 32 },
  { 'E', 33 },
  { 'N', 34 },
  { 'D', 35 },
  { 'S', 36 },
  { 'R', 37 },
  { 'R', 38 },
  { 'W', 39 },
  { 'L', 40 },
  { 'U', 41 },
  { 'N', 42 },
  { 'P', 43 },
  { 'C', 44 },
  { 'I', 45 },
  { 'E', 46 },
  { 'U', 47 },
  { 'P', 48 },
  { 'R', 49 },
  { 'E', 50 },
  { 'M', 51 },
  { 'S', 52 },
  { 'S', 53 },
  { '\t', 29 },
  { ' ', 29 },
  { ':', -3 },
  { '=', -3 },
  { '\t', 30 },
  { '\n', -4 },
  { '\r', -4 },
  { ' ', 30 },
  { '\t', 31 },
  { ' ', 31 },
  { ':', -5 },
  { '=', -5 },
  { '\t', 32 },
  { ' ', 32 },
  { ':', -6 },
  { '=', -6 },
  { 'V', 54 },
  { 'D', 55 },
  { 'P', 56 },
  { 'N', 57 },
  { 'F', 58 },
  { 'H', 59 },
  { 'A', 60 },
  { 'A', 61 },
  { 'D', 62 },
  { 'P', 63 },
  { 'D', 64 },
  { 'D', 65 },
  { 'C', 66 },
  { 'P', 67 },
  { 'R', 68 },
  { 'M', 69 },
  { 'S', 70 },
  { 'F', 71 },
  { 'S', 72 },
  { 'C', 73 },
  { '\t', 51 },
  { ' ', 51 },
  { ':', -7 },
  { '=', -7 },
  { '\t', 52 },
  { ' ', 52 },
  { ':', -8 },
  { '=', -8 },
  { '\t', 53 },
  { ' ', 53 },
  { ':', -9 },
  { '=', -9 },
  { '\t', 54 },
  { ' ', 54 },
  { ':', -10 },
  { '=', -10 },
  { '\t', 55 },
  { '\n', -11 },
  { '\r', -11 },
  { ' ', 55 },
  { ':', -12 },
  { '=', -12 },
  { '?', 74 },
  { '\t', 56 },
  { ' ', 56 },
  { ':', 75 },
  { '=', 75 },
  { '\t', 57 },
  { '\n', -13 },
  { '\r', -13 },
  { ' ', 57 },
  { '\t', 58 },
  { ' ', 58 },
  { ':', -14 },
  { '=', -14 },
  { '\t', 59 },
  { '\n', -15 },
  { '\r', -15 },
  { ' ', 59 },
  { ':', -16 },
  { '=', -16 },
  { '?', 76 },
  { '\t', 60 },
  { ' ', 60 },
  { ':', -17 },
  { '=', -17 },
  { '\t', 61 },
  { ' ', 61 },
  { ':', -18 },
  { '=', -18 },
  { '\t', 62 },
  { ' ', 62 },
  { ':', -19 },
  { '=', -19 },
  { '\t', 63 },
  { '\n', -20 },
  { '\r', -20 },
  { ' ', 63 },
  { '\t', 64 },
  { '\n', -21 },
  { '\r', -21 },
  { ' ', 64 },
  { ':', 77 },
  { '=', 77 },
  { '?', 78 },
  { '\t', 65 },
  { ' ', 65 },
  { ':', -22 },
  { '=', -22 },
  { '\t', 66 },
  { '\n', -23 },
  { '\r', -23 },
  { ' ', 66 },
  { '\t', 67 },
  { ' ', 67 },
  { ':', -24 },
  { '=', -24 },
  { '\t', 68 },
  { ' ', 68 },
  { ':', -25 },
  { '=', -25 },
  { '\t', 69 },
  { '\n', -26 },
  { '\r', -26 },
  { ' ', 69 },
  { '\t', 70 },
  { '\n', -27 },
  { '\r', -27 },
  { ' ', 70 },
  { ':', -28 },
  { '=', -28 },
  { '?', 79 },
  { 'N', 80 },
  { 'F', 81 },
  { '\t', 73 },
  { ' ', 73 },
  { ':', -29 },
  { '=', -29 },
  { '\t', 82 },
  { '\n', -11 },
  { '\r', -11 },
  { ' ', 82 },
  { '?', 74 },
  { '\t', 75 },
  { ' ', 75 },
  { '1', 83 },
  { '\t', 84 },
  { '\n', -15 },
  { '\r', -15 },
  { ' ', 84 },
  { '?', 76 },
  { '\t', 77 },
  { '\n', -30 },
  { '\r', -30 },
  { ' ', 77 },
  { '?', 85 },
  { '\t', 86 },
  { '\n', -21 },
  { '\r', -21 },
  { ' ', 86 },
  { '?', 78 },
  { '\t', 87 },
  { '\n', -27 },
  { '\r', -27 },
  { ' ', 87 },
  { '?', 79 },
  { '\t', 80 },
  { ' ', 80 },
  { ':', -31 },
  { '=', -31 },
  { '\t', 81 },
  { ' ', 81 },
  { ':', -32 },
  { '=', -32 },
  { '\t', 82 },
  { '\n', -11 },
  { '\r', -11 },
  { ' ', 82 },
  { '\t', 83 },
  { '\n', -33 },
  { '\r', -33 },
  { ' ', 83 },
  { '\t', 84 },
  { '\n', -15 },
  { '\r', -15 },
  { ' ', 84 },
  { '\t', 88 },
  { '\n', -30 },
  { '\r', -30 },
  { ' ', 88 },
  { '?', 85 },
  { '\t', 86 },
  { '\n', -21 },
  { '\r', -21 },
  { ' ', 86 },
  { '\t', 87 },
  { '\n', -27 },
  { '\r', -27 },
  { ' ', 87 },
  { '\t', 88 },
  { '\n', -30 },
  { '\r', -30 },
  { ' ', 88 },
};

static const Arc *const states[90] = {
  &arcs[0],
  &arcs[3],
  &arcs[4],
  &arcs[9],
  &arcs[12],
  &arcs[18],
  &arcs[22],
  &arcs[29],
  &arcs[38],
  &arcs[39],
  &arcs[41],
  &arcs[42],
  &arcs[44],
  &arcs[47],
  &arcs[48],
  &arcs[49],
  &arcs[50],
  &arcs[51],
  &arcs[52],
  &arcs[54],
  &arcs[55],
  &arcs[56],
  &arcs[58],
  &arcs[59],
  &arcs[60],
  &arcs[61],
  &arcs[62],
  &arcs[63],
  &arcs[65],
  &arcs[66],
  &arcs[70],
  &arcs[74],
  &arcs[78],
  &arcs[82],
  &arcs[83],
  &arcs[85],
  &arcs[86],
  &arcs[87],
  &arcs[88],
  &arcs[89],
  &arcs[90],
  &arcs[91],
  &arcs[92],
  &arcs[93],
  &arcs[94],
  &arcs[95],
  &arcs[96],
  &arcs[97],
  &arcs[98],
  &arcs[99],
  &arcs[101],
  &arcs[102],
  &arcs[106],
  &arcs[110],
  &arcs[114],
  &arcs[118],
  &arcs[125],
  &arcs[129],
  &arcs[133],
  &arcs[137],
  &arcs[144],
  &arcs[148],
  &arcs[152],
  &arcs[156],
  &arcs[160],
  &arcs[167],
  &arcs[171],
  &arcs[175],
  &arcs[179],
  &arcs[183],
  &arcs[187],
  &arcs[194],
  &arcs[195],
  &arcs[196],
  &arcs[200],
  &arcs[205],
  &arcs[208],
  &arcs[213],
  &arcs[218],
  &arcs[223],
  &arcs[228],
  &arcs[232],
  &arcs[236],
  &arcs[240],
  &arcs[244],
  &arcs[248],
  &arcs[253],
  &arcs[257],
  &arcs[261],
  &arcs[265],
};

static uint16 matchLiteral(ptr s, ptr e, Task task)
{ s=s; e=e; task=task; return 0; }

ptr parseData(ptr s, ptr e, Task task)
{
  ptr p;

#ifdef DISPLAY_AT_CMDS
  {
    ptr c = s;
    printf("\nreceived: ");
    while (c != e)
    {
      if (*c == '\r')         printf("\\r");
      else if (*c == '\n')    printf("\\n");
      else                     putchar(*c);

      c++;
    }
  }
#endif

#ifdef TEST_HARNESS
  task = task;
#endif
  for(; (p = findEndOfPacket(s, e)) != 0; s = p)
  {
    if(p == s+1)
    {
      /* Silently discard one character; no packets are that short */
      continue;
    }
    else if(matchLiteral(s, p, task))
    {
      continue;
    }
    else
    {
      union {
        struct aghfpHandleDialParse aghfpHandleDialParse;
        struct aghfpHandleMemoryDialParse aghfpHandleMemoryDialParse;
        struct aghfpHandleAvailableCodecs aghfpHandleAvailableCodecs;
        struct aghfpHandleWbsCodecNegotiation aghfpHandleWbsCodecNegotiation;
        struct aghfpHandleBiaParse aghfpHandleBiaParse;
        struct aghfpHandleVgmParse aghfpHandleVgmParse;
        struct aghfpHandleVgsParse aghfpHandleVgsParse;
        struct aghfpHandleVtsParse aghfpHandleVtsParse;
        struct aghfpHandleBievParse aghfpHandleBievParse;
        struct aghfpHandleBindParse aghfpHandleBindParse;
        struct aghfpHandleBrsfReqParse aghfpHandleBrsfReqParse;
        struct aghfpHandleBtrhSetStatusParse aghfpHandleBtrhSetStatusParse;
        struct aghfpHandleBvraParse aghfpHandleBvraParse;
        struct aghfpHandleCcwaParse aghfpHandleCcwaParse;
        struct aghfpHandleChldParse aghfpHandleChldParse;
        struct aghfpHandleCkpdParse aghfpHandleCkpdParse;
        struct aghfpHandleClipParse aghfpHandleClipParse;
        struct aghfpHandleCmerReqParse aghfpHandleCmerReqParse;
        struct aghfpHandleCopsFormatParse aghfpHandleCopsFormatParse;
        struct aghfpHandleNrecParse aghfpHandleNrecParse;
        struct aghfpHandleFeatureNegotiation aghfpHandleFeatureNegotiation;
        struct aghfpHandleFeatureNegotiationWithBandwidth aghfpHandleFeatureNegotiationWithBandwidth;
        struct aghfpHandleReponseCSRSupportedFeaturesCodecsBw aghfpHandleReponseCSRSupportedFeaturesCodecsBw;
        struct aghfpHandleReponseCSRSupportedFeatures aghfpHandleReponseCSRSupportedFeatures;
      } u, *uu = &u;
      int state = 0;
      ptr t = s;
      while(t != e && state >= 0)
      {
        char m = my_toupper((char) *t);
        const Arc *a = states[state];
        const Arc *const last_a = states[state+1];
#ifndef TEST_HARNESS
        a = (const Arc *) (void *) UtilFind(0xFFFF, (uint16) m, (const uint16 *) (void *) &a[0].c, 0, sizeof(Arc), (uint16) (last_a - a));
#endif
#ifdef TEST_HARNESS
        while(a != last_a && a->c != m) a++;
#endif
        /*lint -e{801} suppress goto is deprecated */
        if(!a) goto unrecognised;
        state = a->to;
        ++t;
      }
      switch(-state)
      {
        case 1:
          if(match1(skip1(skipOnce1(getString(skip1(t, e), e, &uu->aghfpHandleDialParse.number), e), e), e))
          {
#ifndef TEST_HARNESS
            aghfpHandleDialParse(task, &uu->aghfpHandleDialParse);
#endif
#ifdef TEST_HARNESS
            printf("Called aghfpHandleDialParse");
            printString("number", &uu->aghfpHandleDialParse.number);
            putchar('\n');
#endif
            continue;
          }
          if(match1(skip1(skipOnce1(getString(skip1(matchChar(skip1(t, e), e, '>'), e), e, &uu->aghfpHandleMemoryDialParse.number), e), e), e))
          {
#ifndef TEST_HARNESS
            aghfpHandleMemoryDialParse(task, &uu->aghfpHandleMemoryDialParse);
#endif
#ifdef TEST_HARNESS
            printf("Called aghfpHandleMemoryDialParse");
            printString("number", &uu->aghfpHandleMemoryDialParse.number);
            putchar('\n');
#endif
            continue;
          }
          break;
        case 2:
          if(t)
          {
#ifndef TEST_HARNESS
            aghfpHandleAtaParse(task);
#endif
#ifdef TEST_HARNESS
            printf("Called aghfpHandleAtaParse");
            putchar('\n');
#endif
            continue;
          }
          break;
        case 3:
          if(match1(skip1(loop1(skip1(t, e), e, &uu->aghfpHandleAvailableCodecs.codecs), e), e))
          {
#ifndef TEST_HARNESS
            aghfpHandleAvailableCodecs(task, &uu->aghfpHandleAvailableCodecs);
#endif
#ifdef TEST_HARNESS
            printf("Called aghfpHandleAvailableCodecs");
            {
              uint16 i;
              struct region_aghfpHandleAvailableCodecs_codecs *r = &uu->aghfpHandleAvailableCodecs.codecs;
              printf(" codecs={");
              for(i = 0; i < r->count; ++i)
              {
                struct value_aghfpHandleAvailableCodecs_codecs t = get_aghfpHandleAvailableCodecs_codecs(r, i);
                putchar('{');
                printf(" codec=%d", t.codec);
                putchar('}');
              }
              putchar('}');
            }
            putchar('\n');
#endif
            continue;
          }
          break;
        case 4:
          if(t)
          {
#ifndef TEST_HARNESS
            aghfpHandleWbsCodecConnection(task);
#endif
#ifdef TEST_HARNESS
            printf("Called aghfpHandleWbsCodecConnection");
            putchar('\n');
#endif
            continue;
          }
          break;
        case 5:
          if(match1(skip1(UtilGetNumber(skip1(t, e), e, &uu->aghfpHandleWbsCodecNegotiation.codec), e), e))
          {
#ifndef TEST_HARNESS
            aghfpHandleWbsCodecNegotiation(task, &uu->aghfpHandleWbsCodecNegotiation);
#endif
#ifdef TEST_HARNESS
            printf("Called aghfpHandleWbsCodecNegotiation");
            printf(" codec=%d", uu->aghfpHandleWbsCodecNegotiation.codec);
            putchar('\n');
#endif
            continue;
          }
          break;
        case 6:
          if(match1(skip1(getWildString(skip1(t, e), e, &uu->aghfpHandleBiaParse.indicators), e), e))
          {
#ifndef TEST_HARNESS
            aghfpHandleBiaParse(task, &uu->aghfpHandleBiaParse);
#endif
#ifdef TEST_HARNESS
            printf("Called aghfpHandleBiaParse");
            printString("indicators", &uu->aghfpHandleBiaParse.indicators);
            putchar('\n');
#endif
            continue;
          }
          break;
        case 7:
          if(match1(skip1(UtilGetNumber(skip1(t, e), e, &uu->aghfpHandleVgmParse.gain), e), e))
          {
#ifndef TEST_HARNESS
            aghfpHandleVgmParse(task, &uu->aghfpHandleVgmParse);
#endif
#ifdef TEST_HARNESS
            printf("Called aghfpHandleVgmParse");
            printf(" gain=%d", uu->aghfpHandleVgmParse.gain);
            putchar('\n');
#endif
            continue;
          }
          break;
        case 8:
          if(match1(skip1(UtilGetNumber(skip1(t, e), e, &uu->aghfpHandleVgsParse.volume), e), e))
          {
#ifndef TEST_HARNESS
            aghfpHandleVgsParse(task, &uu->aghfpHandleVgsParse);
#endif
#ifdef TEST_HARNESS
            printf("Called aghfpHandleVgsParse");
            printf(" volume=%d", uu->aghfpHandleVgsParse.volume);
            putchar('\n');
#endif
            continue;
          }
          break;
        case 9:
          if(match1(skip1(getString(skip1(t, e), e, &uu->aghfpHandleVtsParse.code), e), e))
          {
#ifndef TEST_HARNESS
            aghfpHandleVtsParse(task, &uu->aghfpHandleVtsParse);
#endif
#ifdef TEST_HARNESS
            printf("Called aghfpHandleVtsParse");
            printString("code", &uu->aghfpHandleVtsParse.code);
            putchar('\n');
#endif
            continue;
          }
          break;
        case 10:
          if(match1(skip1(UtilGetNumber(skip1(skipOnce1(skip1(UtilGetNumber(skip1(t, e), e, &uu->aghfpHandleBievParse.assignedNum), e), e), e), e, &uu->aghfpHandleBievParse.value), e), e))
          {
#ifndef TEST_HARNESS
            aghfpHandleBievParse(task, &uu->aghfpHandleBievParse);
#endif
#ifdef TEST_HARNESS
            printf("Called aghfpHandleBievParse");
            printf(" assignedNum=%d", uu->aghfpHandleBievParse.assignedNum);
            printf(" value=%d", uu->aghfpHandleBievParse.value);
            putchar('\n');
#endif
            continue;
          }
          break;
        case 11:
          if(t)
          {
#ifndef TEST_HARNESS
            aghfpHandleBindStatusRequestParse(task);
#endif
#ifdef TEST_HARNESS
            printf("Called aghfpHandleBindStatusRequestParse");
            putchar('\n');
#endif
            continue;
          }
          break;
        case 12:
          if(match1(skip1(loop2(skip1(t, e), e, &uu->aghfpHandleBindParse.indicators), e), e))
          {
#ifndef TEST_HARNESS
            aghfpHandleBindParse(task, &uu->aghfpHandleBindParse);
#endif
#ifdef TEST_HARNESS
            printf("Called aghfpHandleBindParse");
            {
              uint16 i;
              struct region_aghfpHandleBindParse_indicators *r = &uu->aghfpHandleBindParse.indicators;
              printf(" indicators={");
              for(i = 0; i < r->count; ++i)
              {
                struct value_aghfpHandleBindParse_indicators t = get_aghfpHandleBindParse_indicators(r, i);
                putchar('{');
                printf(" indicator=%d", t.indicator);
                putchar('}');
              }
              putchar('}');
            }
            putchar('\n');
#endif
            continue;
          }
          if(match1(skip1(skip2(skip1(t, e), e), e), e))
          {
#ifndef TEST_HARNESS
            aghfpHandleBindSupportRequestParse(task);
#endif
#ifdef TEST_HARNESS
            printf("Called aghfpHandleBindSupportRequestParse");
            putchar('\n');
#endif
            continue;
          }
          break;
        case 13:
          if(t)
          {
#ifndef TEST_HARNESS
            aghfpHandleBldnParse(task);
#endif
#ifdef TEST_HARNESS
            printf("Called aghfpHandleBldnParse");
            putchar('\n');
#endif
            continue;
          }
          break;
        case 14:
          if(match1(skip1(UtilGetNumber(skip1(t, e), e, &uu->aghfpHandleBrsfReqParse.supportedFeatures), e), e))
          {
#ifndef TEST_HARNESS
            aghfpHandleBrsfReqParse(task, &uu->aghfpHandleBrsfReqParse);
#endif
#ifdef TEST_HARNESS
            printf("Called aghfpHandleBrsfReqParse");
            printf(" supportedFeatures=%d", uu->aghfpHandleBrsfReqParse.supportedFeatures);
            putchar('\n');
#endif
            continue;
          }
          break;
        case 15:
          if(t)
          {
#ifndef TEST_HARNESS
            aghfpHandleBtrhStatusRequestParse(task);
#endif
#ifdef TEST_HARNESS
            printf("Called aghfpHandleBtrhStatusRequestParse");
            putchar('\n');
#endif
            continue;
          }
          break;
        case 16:
          if(match1(skip1(UtilGetNumber(skip1(t, e), e, &uu->aghfpHandleBtrhSetStatusParse.cmd), e), e))
          {
#ifndef TEST_HARNESS
            aghfpHandleBtrhSetStatusParse(task, &uu->aghfpHandleBtrhSetStatusParse);
#endif
#ifdef TEST_HARNESS
            printf("Called aghfpHandleBtrhSetStatusParse");
            printf(" cmd=%d", uu->aghfpHandleBtrhSetStatusParse.cmd);
            putchar('\n');
#endif
            continue;
          }
          break;
        case 17:
          if(match1(skip1(UtilGetNumber(skip1(t, e), e, &uu->aghfpHandleBvraParse.state), e), e))
          {
#ifndef TEST_HARNESS
            aghfpHandleBvraParse(task, &uu->aghfpHandleBvraParse);
#endif
#ifdef TEST_HARNESS
            printf("Called aghfpHandleBvraParse");
            printf(" state=%d", uu->aghfpHandleBvraParse.state);
            putchar('\n');
#endif
            continue;
          }
          break;
        case 18:
          if(match1(skip1(UtilGetNumber(skip1(t, e), e, &uu->aghfpHandleCcwaParse.state), e), e))
          {
#ifndef TEST_HARNESS
            aghfpHandleCcwaParse(task, &uu->aghfpHandleCcwaParse);
#endif
#ifdef TEST_HARNESS
            printf("Called aghfpHandleCcwaParse");
            printf(" state=%d", uu->aghfpHandleCcwaParse.state);
            putchar('\n');
#endif
            continue;
          }
          break;
        case 19:
          if(match1(skip1(skip2(skip1(t, e), e), e), e))
          {
#ifndef TEST_HARNESS
            aghfpHandleChldSupportReqParse(task);
#endif
#ifdef TEST_HARNESS
            printf("Called aghfpHandleChldSupportReqParse");
            putchar('\n');
#endif
            continue;
          }
          if(match1(skip1(getString(skip1(t, e), e, &uu->aghfpHandleChldParse.cmd), e), e))
          {
#ifndef TEST_HARNESS
            aghfpHandleChldParse(task, &uu->aghfpHandleChldParse);
#endif
#ifdef TEST_HARNESS
            printf("Called aghfpHandleChldParse");
            printString("cmd", &uu->aghfpHandleChldParse.cmd);
            putchar('\n');
#endif
            continue;
          }
          break;
        case 20:
          if(t)
          {
#ifndef TEST_HARNESS
            aghfpHandleChupParse(task);
#endif
#ifdef TEST_HARNESS
            printf("Called aghfpHandleChupParse");
            putchar('\n');
#endif
            continue;
          }
          break;
        case 21:
          if(t)
          {
#ifndef TEST_HARNESS
            aghfpHandleCindStatusReqParse(task);
#endif
#ifdef TEST_HARNESS
            printf("Called aghfpHandleCindStatusReqParse");
            putchar('\n');
#endif
            continue;
          }
          break;
        case 22:
          if(match1(skip1(UtilGetNumber(skip1(t, e), e, &uu->aghfpHandleCkpdParse.keycode), e), e))
          {
#ifndef TEST_HARNESS
            aghfpHandleCkpdParse(task, &uu->aghfpHandleCkpdParse);
#endif
#ifdef TEST_HARNESS
            printf("Called aghfpHandleCkpdParse");
            printf(" keycode=%d", uu->aghfpHandleCkpdParse.keycode);
            putchar('\n');
#endif
            continue;
          }
          break;
        case 23:
          if(t)
          {
#ifndef TEST_HARNESS
            aghfpHandleClccParse(task);
#endif
#ifdef TEST_HARNESS
            printf("Called aghfpHandleClccParse");
            putchar('\n');
#endif
            continue;
          }
          break;
        case 24:
          if(match1(skip1(UtilGetNumber(skip1(t, e), e, &uu->aghfpHandleClipParse.state), e), e))
          {
#ifndef TEST_HARNESS
            aghfpHandleClipParse(task, &uu->aghfpHandleClipParse);
#endif
#ifdef TEST_HARNESS
            printf("Called aghfpHandleClipParse");
            printf(" state=%d", uu->aghfpHandleClipParse.state);
            putchar('\n');
#endif
            continue;
          }
          break;
        case 25:
          if(match1(skip1(UtilGetNumber(skip1(skipOnce1(skip1(UtilGetNumber(skip1(skipOnce1(skip1(UtilGetNumber(skip1(skipOnce1(skip1(UtilGetNumber(skip1(t, e), e, &uu->aghfpHandleCmerReqParse.mode), e), e), e), e, &uu->aghfpHandleCmerReqParse.keyp), e), e), e), e, &uu->aghfpHandleCmerReqParse.disp), e), e), e), e, &uu->aghfpHandleCmerReqParse.ind), e), e))
          {
#ifndef TEST_HARNESS
            aghfpHandleCmerReqParse(task, &uu->aghfpHandleCmerReqParse);
#endif
#ifdef TEST_HARNESS
            printf("Called aghfpHandleCmerReqParse");
            printf(" mode=%d", uu->aghfpHandleCmerReqParse.mode);
            printf(" keyp=%d", uu->aghfpHandleCmerReqParse.keyp);
            printf(" disp=%d", uu->aghfpHandleCmerReqParse.disp);
            printf(" ind=%d", uu->aghfpHandleCmerReqParse.ind);
            putchar('\n');
#endif
            continue;
          }
          break;
        case 26:
          if(t)
          {
#ifndef TEST_HARNESS
            aghfpHandleCnumParse(task);
#endif
#ifdef TEST_HARNESS
            printf("Called aghfpHandleCnumParse");
            putchar('\n');
#endif
            continue;
          }
          break;
        case 27:
          if(t)
          {
#ifndef TEST_HARNESS
            aghfpHandleCopsStatusParse(task);
#endif
#ifdef TEST_HARNESS
            printf("Called aghfpHandleCopsStatusParse");
            putchar('\n');
#endif
            continue;
          }
          break;
        case 28:
          if(match1(skip1(UtilGetNumber(skip1(skipOnce1(skip1(UtilGetNumber(skip1(t, e), e, &uu->aghfpHandleCopsFormatParse.mode), e), e), e), e, &uu->aghfpHandleCopsFormatParse.format), e), e))
          {
#ifndef TEST_HARNESS
            aghfpHandleCopsFormatParse(task, &uu->aghfpHandleCopsFormatParse);
#endif
#ifdef TEST_HARNESS
            printf("Called aghfpHandleCopsFormatParse");
            printf(" mode=%d", uu->aghfpHandleCopsFormatParse.mode);
            printf(" format=%d", uu->aghfpHandleCopsFormatParse.format);
            putchar('\n');
#endif
            continue;
          }
          break;
        case 29:
          if(match1(skip1(UtilGetNumber(skip1(t, e), e, &uu->aghfpHandleNrecParse.state), e), e))
          {
#ifndef TEST_HARNESS
            aghfpHandleNrecParse(task, &uu->aghfpHandleNrecParse);
#endif
#ifdef TEST_HARNESS
            printf("Called aghfpHandleNrecParse");
            printf(" state=%d", uu->aghfpHandleNrecParse.state);
            putchar('\n');
#endif
            continue;
          }
          break;
        case 30:
          if(t)
          {
#ifndef TEST_HARNESS
            aghfpHandleCindSupportReqParse(task);
#endif
#ifdef TEST_HARNESS
            printf("Called aghfpHandleCindSupportReqParse");
            putchar('\n');
#endif
            continue;
          }
          break;
        case 31:
          if(match1(skip1(skip3(skip1(UtilGetNumber(skip1(skipOnce1(skip1(UtilGetNumber(skip1(skip3(skip1(t, e), e), e), e, &uu->aghfpHandleFeatureNegotiation.ind), e), e), e), e, &uu->aghfpHandleFeatureNegotiation.val), e), e), e), e))
          {
#ifndef TEST_HARNESS
            aghfpHandleFeatureNegotiation(task, &uu->aghfpHandleFeatureNegotiation);
#endif
#ifdef TEST_HARNESS
            printf("Called aghfpHandleFeatureNegotiation");
            printf(" ind=%d", uu->aghfpHandleFeatureNegotiation.ind);
            printf(" val=%d", uu->aghfpHandleFeatureNegotiation.val);
            putchar('\n');
#endif
            continue;
          }
          if(match1(skip1(skip3(UtilGetNumber(skip1(skipOnce1(UtilGetNumber(skip3(skip1(skipOnce1(skip1(skip3(skip1(UtilGetNumber(skip1(skipOnce1(skip1(UtilGetNumber(skip1(skip3(skip1(t, e), e), e), e, &uu->aghfpHandleFeatureNegotiationWithBandwidth.ind0), e), e), e), e, &uu->aghfpHandleFeatureNegotiationWithBandwidth.val0), e), e), e), e), e), e), e, &uu->aghfpHandleFeatureNegotiationWithBandwidth.ind1), e), e), e, &uu->aghfpHandleFeatureNegotiationWithBandwidth.val1), e), e), e))
          {
#ifndef TEST_HARNESS
            aghfpHandleFeatureNegotiationWithBandwidth(task, &uu->aghfpHandleFeatureNegotiationWithBandwidth);
#endif
#ifdef TEST_HARNESS
            printf("Called aghfpHandleFeatureNegotiationWithBandwidth");
            printf(" ind0=%d", uu->aghfpHandleFeatureNegotiationWithBandwidth.ind0);
            printf(" val0=%d", uu->aghfpHandleFeatureNegotiationWithBandwidth.val0);
            printf(" ind1=%d", uu->aghfpHandleFeatureNegotiationWithBandwidth.ind1);
            printf(" val1=%d", uu->aghfpHandleFeatureNegotiationWithBandwidth.val1);
            putchar('\n');
#endif
            continue;
          }
          break;
        case 32:
          if(match1(skip1(getWildString(skip1(skipOnce1(UtilGetNumber(skip1(skipOnce1(skip1(UtilGetNumber(skip1(skipOnce1(skip1(UtilGetNumber(skip1(skipOnce1(skip1(UtilGetNumber(skip1(skipOnce1(skip1(UtilGetNumber(skip1(skipOnce1(skip1(UtilGetNumber(skip1(skipOnce1(skip1(UtilGetNumber(skip1(t, e), e, &uu->aghfpHandleReponseCSRSupportedFeaturesCodecsBw.callerName), e), e), e), e, &uu->aghfpHandleReponseCSRSupportedFeaturesCodecsBw.rawText), e), e), e), e, &uu->aghfpHandleReponseCSRSupportedFeaturesCodecsBw.smsInd), e), e), e), e, &uu->aghfpHandleReponseCSRSupportedFeaturesCodecsBw.battLevel), e), e), e), e, &uu->aghfpHandleReponseCSRSupportedFeaturesCodecsBw.pwrSource), e), e), e), e, &uu->aghfpHandleReponseCSRSupportedFeaturesCodecsBw.codecs), e), e), e), e, &uu->aghfpHandleReponseCSRSupportedFeaturesCodecsBw.codecBandwidths), e), e), e, &uu->aghfpHandleReponseCSRSupportedFeaturesCodecsBw.ignore), e), e))
          {
#ifndef TEST_HARNESS
            aghfpHandleReponseCSRSupportedFeaturesCodecsBw(task, &uu->aghfpHandleReponseCSRSupportedFeaturesCodecsBw);
#endif
#ifdef TEST_HARNESS
            printf("Called aghfpHandleReponseCSRSupportedFeaturesCodecsBw");
            printf(" callerName=%d", uu->aghfpHandleReponseCSRSupportedFeaturesCodecsBw.callerName);
            printf(" rawText=%d", uu->aghfpHandleReponseCSRSupportedFeaturesCodecsBw.rawText);
            printf(" smsInd=%d", uu->aghfpHandleReponseCSRSupportedFeaturesCodecsBw.smsInd);
            printf(" battLevel=%d", uu->aghfpHandleReponseCSRSupportedFeaturesCodecsBw.battLevel);
            printf(" pwrSource=%d", uu->aghfpHandleReponseCSRSupportedFeaturesCodecsBw.pwrSource);
            printf(" codecs=%d", uu->aghfpHandleReponseCSRSupportedFeaturesCodecsBw.codecs);
            printf(" codecBandwidths=%d", uu->aghfpHandleReponseCSRSupportedFeaturesCodecsBw.codecBandwidths);
            printString("ignore", &uu->aghfpHandleReponseCSRSupportedFeaturesCodecsBw.ignore);
            putchar('\n');
#endif
            continue;
          }
          if(match1(skip1(getWildString(skip1(skipOnce1(skip1(UtilGetNumber(skip1(skipOnce1(skip1(UtilGetNumber(skip1(skipOnce1(skip1(UtilGetNumber(skip1(skipOnce1(skip1(UtilGetNumber(skip1(skipOnce1(skip1(UtilGetNumber(skip1(skipOnce1(skip1(UtilGetNumber(skip1(t, e), e, &uu->aghfpHandleReponseCSRSupportedFeatures.callerName), e), e), e), e, &uu->aghfpHandleReponseCSRSupportedFeatures.rawText), e), e), e), e, &uu->aghfpHandleReponseCSRSupportedFeatures.smsInd), e), e), e), e, &uu->aghfpHandleReponseCSRSupportedFeatures.battLevel), e), e), e), e, &uu->aghfpHandleReponseCSRSupportedFeatures.pwrSource), e), e), e), e, &uu->aghfpHandleReponseCSRSupportedFeatures.codecs), e), e), e), e, &uu->aghfpHandleReponseCSRSupportedFeatures.ignore), e), e))
          {
#ifndef TEST_HARNESS
            aghfpHandleReponseCSRSupportedFeatures(task, &uu->aghfpHandleReponseCSRSupportedFeatures);
#endif
#ifdef TEST_HARNESS
            printf("Called aghfpHandleReponseCSRSupportedFeatures");
            printf(" callerName=%d", uu->aghfpHandleReponseCSRSupportedFeatures.callerName);
            printf(" rawText=%d", uu->aghfpHandleReponseCSRSupportedFeatures.rawText);
            printf(" smsInd=%d", uu->aghfpHandleReponseCSRSupportedFeatures.smsInd);
            printf(" battLevel=%d", uu->aghfpHandleReponseCSRSupportedFeatures.battLevel);
            printf(" pwrSource=%d", uu->aghfpHandleReponseCSRSupportedFeatures.pwrSource);
            printf(" codecs=%d", uu->aghfpHandleReponseCSRSupportedFeatures.codecs);
            printString("ignore", &uu->aghfpHandleReponseCSRSupportedFeatures.ignore);
            putchar('\n');
#endif
            continue;
          }
          break;
        case 33:
          if(t)
          {
#ifndef TEST_HARNESS
            aghfpHandleBinpParse(task);
#endif
#ifdef TEST_HARNESS
            printf("Called aghfpHandleBinpParse");
            putchar('\n');
#endif
            continue;
          }
          break;
        default:
          break;
      }
      /*
        The message does not contain a recognised AT command or response.
        Pass the data on to the application to have a go at 
      */
unrecognised:
#ifndef TEST_HARNESS
      handleUnrecognised(s, (uint16) (p-s), task);
#endif
#ifdef TEST_HARNESS
      printf("Called handleUnrecognised\n");
#endif
    }
  }

  return s;
}

/*
aghfpHandleCkpdParse
   Skip " \t"
   MatchChar A
   MatchChar T
   Skip " \t"
   MatchChar +
   Skip " \t"
   MatchChar C
   MatchChar K
   MatchChar P
   MatchChar D
   Skip " \t"
   Match "=:"
   Skip " \t"
   GetNumber keycode
   Skip " \t"
   Match "\r\n"


aghfpHandleBrsfReqParse
   Skip " \t"
   MatchChar A
   MatchChar T
   Skip " \t"
   MatchChar +
   Skip " \t"
   MatchChar B
   MatchChar R
   MatchChar S
   MatchChar F
   Skip " \t"
   Match "=:"
   Skip " \t"
   GetNumber supportedFeatures
   Skip " \t"
   Match "\r\n"


aghfpHandleCindSupportReqParse
   Skip " \t"
   MatchChar A
   MatchChar T
   Skip " \t"
   MatchChar +
   Skip " \t"
   MatchChar C
   MatchChar I
   MatchChar N
   MatchChar D
   Skip " \t"
   Match "=:"
   Skip " \t"
   Skip "?"
   Skip " \t"
   Match "\r\n"


aghfpHandleCindStatusReqParse
   Skip " \t"
   MatchChar A
   MatchChar T
   Skip " \t"
   MatchChar +
   Skip " \t"
   MatchChar C
   MatchChar I
   MatchChar N
   MatchChar D
   Skip " \t"
   Skip "?"
   Skip " \t"
   Match "\r\n"


aghfpHandleCmerReqParse
   Skip " \t"
   MatchChar A
   MatchChar T
   Skip " \t"
   MatchChar +
   Skip " \t"
   MatchChar C
   MatchChar M
   MatchChar E
   MatchChar R
   Skip " \t"
   Match "=:"
   Skip " \t"
   GetNumber mode
   Skip " \t"
   SkipOnce ",;"
   Skip " \t"
   GetNumber keyp
   Skip " \t"
   SkipOnce ",;"
   Skip " \t"
   GetNumber disp
   Skip " \t"
   SkipOnce ",;"
   Skip " \t"
   GetNumber ind
   Skip " \t"
   Match "\r\n"


aghfpHandleChldSupportReqParse
   Skip " \t"
   MatchChar A
   MatchChar T
   Skip " \t"
   MatchChar +
   Skip " \t"
   MatchChar C
   MatchChar H
   MatchChar L
   MatchChar D
   Skip " \t"
   Match "=:"
   Skip " \t"
   Skip "?"
   Skip " \t"
   Match "\r\n"


aghfpHandleChldParse
   Skip " \t"
   MatchChar A
   MatchChar T
   Skip " \t"
   MatchChar +
   Skip " \t"
   MatchChar C
   MatchChar H
   MatchChar L
   MatchChar D
   Skip " \t"
   Match "=:"
   Skip " \t"
   GetString cmd
   Skip " \t"
   Match "\r\n"


aghfpHandleAtaParse
   Skip " \t"
   MatchChar A
   MatchChar T
   MatchChar A
   Skip " \t"
   Match "\r\n"


aghfpHandleClipParse
   Skip " \t"
   MatchChar A
   MatchChar T
   Skip " \t"
   MatchChar +
   Skip " \t"
   MatchChar C
   MatchChar L
   MatchChar I
   MatchChar P
   Skip " \t"
   Match "=:"
   Skip " \t"
   GetNumber state
   Skip " \t"
   Match "\r\n"


aghfpHandleCcwaParse
   Skip " \t"
   MatchChar A
   MatchChar T
   Skip " \t"
   MatchChar +
   Skip " \t"
   MatchChar C
   MatchChar C
   MatchChar W
   MatchChar A
   Skip " \t"
   Match "=:"
   Skip " \t"
   GetNumber state
   Skip " \t"
   Match "\r\n"


aghfpHandleChupParse
   Skip " \t"
   MatchChar A
   MatchChar T
   Skip " \t"
   MatchChar +
   Skip " \t"
   MatchChar C
   MatchChar H
   MatchChar U
   MatchChar P
   Skip " \t"
   Match "\r\n"


aghfpHandleDialParse
   Skip " \t"
   MatchChar A
   MatchChar T
   MatchChar D
   Skip " \t"
   GetString number
   SkipOnce ",;"
   Skip " \t"
   Match "\r\n"


aghfpHandleMemoryDialParse
   Skip " \t"
   MatchChar A
   MatchChar T
   MatchChar D
   Skip " \t"
   MatchChar >
   Skip " \t"
   GetString number
   SkipOnce ",;"
   Skip " \t"
   Match "\r\n"


aghfpHandleBldnParse
   Skip " \t"
   MatchChar A
   MatchChar T
   Skip " \t"
   MatchChar +
   Skip " \t"
   MatchChar B
   MatchChar L
   MatchChar D
   MatchChar N
   Skip " \t"
   Match "\r\n"


aghfpHandleNrecParse
   Skip " \t"
   MatchChar A
   MatchChar T
   Skip " \t"
   MatchChar +
   Skip " \t"
   MatchChar N
   MatchChar R
   MatchChar E
   MatchChar C
   Skip " \t"
   Match "=:"
   Skip " \t"
   GetNumber state
   Skip " \t"
   Match "\r\n"


aghfpHandleBvraParse
   Skip " \t"
   MatchChar A
   MatchChar T
   Skip " \t"
   MatchChar +
   Skip " \t"
   MatchChar B
   MatchChar V
   MatchChar R
   MatchChar A
   Skip " \t"
   Match "=:"
   Skip " \t"
   GetNumber state
   Skip " \t"
   Match "\r\n"


aghfpHandleBinpParse
   Skip " \t"
   MatchChar A
   MatchChar T
   Skip " \t"
   MatchChar +
   Skip " \t"
   MatchChar B
   MatchChar I
   MatchChar N
   MatchChar P
   Skip " \t"
   Match "=:"
   Skip " \t"
   MatchChar 1
   Skip " \t"
   Match "\r\n"


aghfpHandleVtsParse
   Skip " \t"
   MatchChar A
   MatchChar T
   Skip " \t"
   MatchChar +
   Skip " \t"
   MatchChar V
   MatchChar T
   MatchChar S
   Skip " \t"
   Match "=:"
   Skip " \t"
   GetString code
   Skip " \t"
   Match "\r\n"


aghfpHandleVgmParse
   Skip " \t"
   MatchChar A
   MatchChar T
   Skip " \t"
   MatchChar +
   Skip " \t"
   MatchChar V
   MatchChar G
   MatchChar M
   Skip " \t"
   Match "=:"
   Skip " \t"
   GetNumber gain
   Skip " \t"
   Match "\r\n"


aghfpHandleVgsParse
   Skip " \t"
   MatchChar A
   MatchChar T
   Skip " \t"
   MatchChar +
   Skip " \t"
   MatchChar V
   MatchChar G
   MatchChar S
   Skip " \t"
   Match "=:"
   Skip " \t"
   GetNumber volume
   Skip " \t"
   Match "\r\n"


aghfpHandleBtrhStatusRequestParse
   Skip " \t"
   MatchChar A
   MatchChar T
   Skip " \t"
   MatchChar +
   Skip " \t"
   MatchChar B
   MatchChar T
   MatchChar R
   MatchChar H
   Skip " \t"
   Skip "?"
   Skip " \t"
   Match "\r\n"


aghfpHandleBtrhSetStatusParse
   Skip " \t"
   MatchChar A
   MatchChar T
   Skip " \t"
   MatchChar +
   Skip " \t"
   MatchChar B
   MatchChar T
   MatchChar R
   MatchChar H
   Skip " \t"
   Match "=:"
   Skip " \t"
   GetNumber cmd
   Skip " \t"
   Match "\r\n"


aghfpHandleCnumParse
   Skip " \t"
   MatchChar A
   MatchChar T
   Skip " \t"
   MatchChar +
   Skip " \t"
   MatchChar C
   MatchChar N
   MatchChar U
   MatchChar M
   Skip " \t"
   Match "\r\n"


aghfpHandleClccParse
   Skip " \t"
   MatchChar A
   MatchChar T
   Skip " \t"
   MatchChar +
   Skip " \t"
   MatchChar C
   MatchChar L
   MatchChar C
   MatchChar C
   Skip " \t"
   Match "\r\n"


aghfpHandleCopsFormatParse
   Skip " \t"
   MatchChar A
   MatchChar T
   Skip " \t"
   MatchChar +
   Skip " \t"
   MatchChar C
   MatchChar O
   MatchChar P
   MatchChar S
   Skip " \t"
   Match "=:"
   Skip " \t"
   GetNumber mode
   Skip " \t"
   SkipOnce ",;"
   Skip " \t"
   GetNumber format
   Skip " \t"
   Match "\r\n"


aghfpHandleCopsStatusParse
   Skip " \t"
   MatchChar A
   MatchChar T
   Skip " \t"
   MatchChar +
   Skip " \t"
   MatchChar C
   MatchChar O
   MatchChar P
   MatchChar S
   Skip " \t"
   Skip "?"
   Skip " \t"
   Match "\r\n"


aghfpHandleBiaParse
   Skip " \t"
   MatchChar A
   MatchChar T
   Skip " \t"
   MatchChar +
   Skip " \t"
   MatchChar B
   MatchChar I
   MatchChar A
   Skip " \t"
   Match "=:"
   Skip " \t"
   GetWildString indicators
   Skip " \t"
   Match "\r\n"


aghfpHandleReponseCSRSupportedFeaturesCodecsBw
   Skip " \t"
   MatchChar A
   MatchChar T
   Skip " \t"
   MatchChar +
   Skip " \t"
   MatchChar C
   MatchChar S
   MatchChar R
   MatchChar S
   MatchChar F
   Skip " \t"
   Match "=:"
   Skip " \t"
   GetNumber callerName
   Skip " \t"
   SkipOnce ",;"
   Skip " \t"
   GetNumber rawText
   Skip " \t"
   SkipOnce ",;"
   Skip " \t"
   GetNumber smsInd
   Skip " \t"
   SkipOnce ",;"
   Skip " \t"
   GetNumber battLevel
   Skip " \t"
   SkipOnce ",;"
   Skip " \t"
   GetNumber pwrSource
   Skip " \t"
   SkipOnce ",;"
   Skip " \t"
   GetNumber codecs
   Skip " \t"
   SkipOnce ",;"
   Skip " \t"
   GetNumber codecBandwidths
   SkipOnce ",;"
   Skip " \t"
   GetWildString ignore
   Skip " \t"
   Match "\r\n"


aghfpHandleReponseCSRSupportedFeatures
   Skip " \t"
   MatchChar A
   MatchChar T
   Skip " \t"
   MatchChar +
   Skip " \t"
   MatchChar C
   MatchChar S
   MatchChar R
   MatchChar S
   MatchChar F
   Skip " \t"
   Match "=:"
   Skip " \t"
   GetNumber callerName
   Skip " \t"
   SkipOnce ",;"
   Skip " \t"
   GetNumber rawText
   Skip " \t"
   SkipOnce ",;"
   Skip " \t"
   GetNumber smsInd
   Skip " \t"
   SkipOnce ",;"
   Skip " \t"
   GetNumber battLevel
   Skip " \t"
   SkipOnce ",;"
   Skip " \t"
   GetNumber pwrSource
   Skip " \t"
   SkipOnce ",;"
   Skip " \t"
   GetNumber codecs
   Skip " \t"
   SkipOnce ",;"
   Skip " \t"
   GetWildString ignore
   Skip " \t"
   Match "\r\n"


aghfpHandleFeatureNegotiation
   Skip " \t"
   MatchChar A
   MatchChar T
   Skip " \t"
   MatchChar +
   Skip " \t"
   MatchChar C
   MatchChar S
   MatchChar R
   MatchChar F
   MatchChar N
   Skip " \t"
   Match "=:"
   Skip " \t"
   Skip "()"
   Skip " \t"
   GetNumber ind
   Skip " \t"
   SkipOnce ",;"
   Skip " \t"
   GetNumber val
   Skip " \t"
   Skip "()"
   Skip " \t"
   Match "\r\n"


aghfpHandleFeatureNegotiationWithBandwidth
   Skip " \t"
   MatchChar A
   MatchChar T
   Skip " \t"
   MatchChar +
   Skip " \t"
   MatchChar C
   MatchChar S
   MatchChar R
   MatchChar F
   MatchChar N
   Skip " \t"
   Match "=:"
   Skip " \t"
   Skip "()"
   Skip " \t"
   GetNumber ind0
   Skip " \t"
   SkipOnce ",;"
   Skip " \t"
   GetNumber val0
   Skip " \t"
   Skip "()"
   Skip " \t"
   SkipOnce ",;"
   Skip " \t"
   Skip "()"
   GetNumber ind1
   SkipOnce ",;"
   Skip " \t"
   GetNumber val1
   Skip "()"
   Skip " \t"
   Match "\r\n"


aghfpHandleWbsCodecNegotiation
   Skip " \t"
   MatchChar A
   MatchChar T
   Skip " \t"
   MatchChar +
   Skip " \t"
   MatchChar B
   MatchChar C
   MatchChar S
   Skip " \t"
   Match "=:"
   Skip " \t"
   GetNumber codec
   Skip " \t"
   Match "\r\n"


aghfpHandleWbsCodecConnection
   Skip " \t"
   MatchChar A
   MatchChar T
   Skip " \t"
   MatchChar +
   Skip " \t"
   MatchChar B
   MatchChar C
   MatchChar C
   Skip " \t"
   Match "\r\n"


aghfpHandleAvailableCodecs
   Skip " \t"
   MatchChar A
   MatchChar T
   Skip " \t"
   MatchChar +
   Skip " \t"
   MatchChar B
   MatchChar A
   MatchChar C
   Skip " \t"
   Match "=:"
   Skip " \t"
   (Loop codecs 1 10   GetNumber codec
   Skip " \t"
   SkipOnce ",;"
   Skip " \t"
)
   Skip " \t"
   Match "\r\n"


aghfpHandleBindParse
   Skip " \t"
   MatchChar A
   MatchChar T
   Skip " \t"
   MatchChar +
   Skip " \t"
   MatchChar B
   MatchChar I
   MatchChar N
   MatchChar D
   Skip " \t"
   Match "=:"
   Skip " \t"
   (Loop indicators 1 10   GetNumber indicator
   Skip " \t"
   SkipOnce ",;"
   Skip " \t"
)
   Skip " \t"
   Match "\r\n"


aghfpHandleBindSupportRequestParse
   Skip " \t"
   MatchChar A
   MatchChar T
   Skip " \t"
   MatchChar +
   Skip " \t"
   MatchChar B
   MatchChar I
   MatchChar N
   MatchChar D
   Skip " \t"
   Match "=:"
   Skip " \t"
   Skip "?"
   Skip " \t"
   Match "\r\n"


aghfpHandleBindStatusRequestParse
   Skip " \t"
   MatchChar A
   MatchChar T
   Skip " \t"
   MatchChar +
   Skip " \t"
   MatchChar B
   MatchChar I
   MatchChar N
   MatchChar D
   Skip " \t"
   Skip "?"
   Skip " \t"
   Match "\r\n"


aghfpHandleBievParse
   Skip " \t"
   MatchChar A
   MatchChar T
   Skip " \t"
   MatchChar +
   Skip " \t"
   MatchChar B
   MatchChar I
   MatchChar E
   MatchChar V
   Skip " \t"
   Match "=:"
   Skip " \t"
   GetNumber assignedNum
   Skip " \t"
   SkipOnce ",;"
   Skip " \t"
   GetNumber value
   Skip " \t"
   Match "\r\n"


*/
