asm_files = alias_reduction.asm \
compensation_for_freq_inversion.asm \
crc_check.asm \
decoder_state.asm \
fillbitres.asm \
frame_decode.asm \
getbitresbits.asm \
getbits.asm \
global_variables.asm \
imdct_windowing_overlapadd.asm \
init_decoder.asm \
jointstereo_processing.asm \
mp3_api.asm \
mp3_ff_rew.asm \
mp3dec_api.asm \
read_header.asm \
read_huffman.asm \
read_scalefactors.asm \
read_sideinfo.asm \
reorder_spectrum.asm \
requantise_subband.asm \
requantise_subbandsample.asm \
reset_decoder.asm \
seek.asm \
silence_decoder.asm \
subband_reconstruction.asm \
synthesis_filterbank.asm

header_files = mp3_library.h \
mp3.h


$(eval $(call header_rules,$(header_files)))

$(eval $(call rules,$(asm_files)))

# one line per variant...
$(eval $(call rules_variant,debug,$(FL_DEBUG),$(asm_files)))
$(foreach hw,$(KAL_BASE_REG_CORES), \
  $(eval $(call rules_variant_core,base_regs,$(FL_BASE_REG),$(asm_files),$(hw))) \
)

$(eval $(call rules_variant,flash,-DMP3DEC_USE_FLASH_FOR_CODE,$(asm_files)))

$(eval $(call rules_variant,zero_flash,-DMP3DEC_ZERO_FLASH,$(asm_files)))

$(eval $(call rules_variant,external,-DMP3_USE_EXTERNAL_MEMORY,$(asm_files)))

