/*
 * THIS FILE IS AUTOGENERATED, DO NOT EDIT!
 *
 * generated by gattdbgen from gatt_broadcast_server/gatt_broadcast_server_db.dbi_
 */
#ifndef __GATT_BROADCAST_SERVER_DB_H
#define __GATT_BROADCAST_SERVER_DB_H

#include <csrtypes.h>

#define HANDLE_BROADCAST_SERVICE        (0x0001)
#define HANDLE_BROADCAST_SERVICE_END    (0xffff)
#define HANDLE_BROADCAST_VERSION        (0x0003)
#define HANDLE_BROADCAST_ADDRESS        (0x0005)
#define HANDLE_BROADCAST_STATUS         (0x0007)
#define HANDLE_BROADCAST_SECURITY_KEY   (0x0009)
#define HANDLE_BROADCAST_STREAM_SERVICE_RECORDS (0x000b)
#define HANDLE_BROADCAST_IDENTIFIER     (0x000d)

uint16 *GattGetDatabase(uint16 *len);
uint16 GattGetDatabaseSize(void);

#endif

/* End-of-File */
